### ISSUE TITLE
Unknown Error when logging in Xiaomi Account

### ISSUE THREAD

**Issue by jiangyiqi99** [AlexxIT/XiaomiGateway3#1640]
[home-assistant_xiaomi_gateway3_2025-08-18T10-52-15.915Z.log](https://github.com/user-attachments/files/21833562/home-assistant_xiaomi_gateway3_2025-08-18T10-52-15.915Z.log)

**Comment by mr-wixy** [comment]
I’m experiencing the same issue.

**Comment by jiangyiqi99** [comment]
[home-assistant_xiaomi_gateway3_2025-08-19T03-23-31.222Z.log](https://github.com/user-attachments/files/21847599/home-assistant_xiaomi_gateway3_2025-08-19T03-23-31.222Z.log)

According to my testing of main branch, this bug has completely fixed at this commit.
My account can login with captcha & SMS OTP. That means my account supports phone verification, but needs captcha.

**Comment by jiangyiqi99** [comment]
I may close this issue after others testing the main branch or after another release version.

**Comment by MrGuAm** [comment]
the latest master version is OK. 
thankQ so much

<img width="802" height="564" alt="Image" src="https://github.com/user-attachments/assets/bf46f4c4-789d-43d2-9387-7f0b9a381f1b" />

<img width="820" height="522" alt="Image" src="https://github.com/user-attachments/assets/636da94d-7c64-4a69-bb3d-c727858d551c" />

<img width="2314" height="844" alt="Image" src="https://github.com/user-attachments/assets/593f1262-9d2e-4209-a29a-64d400c7faef" />

**Comment by zcoo999** [comment]
I still have some unresolved issues.

1、Using my ChinaXiaomi account, when I entered my phone number and correct password on the master branch, 
I received the prompt: **"Unknown error occurred".**

2、After binding an email to this Xiaomi account

I re-entered the same phone number and password

The system then prompted that a verification code had been sent to my email

However, after entering the correct verification code received via email, 
I still encountered the same **"Unknown error occurred"** 
what happen？

**Comment by lemIY** [comment]
Регистратор: custom_components.xiaomi_gateway3.config_flow
Источник: custom_components/xiaomi_gateway3/core/xiaomi_cloud.py:221
интеграция: Xiaomi Gateway 3 ([документация](https://github.com/AlexxIT/XiaomiGateway3), [проблемы](https://github.com/AlexxIT/XiaomiGateway3/issues))
Зафиксировано первый раз: 01:08:25 (1 случай)
Зафиксировано последний раз: 01:08:25

Can't login
Traceback (most recent call last):
  File "/config/custom_components/xiaomi_gateway3/core/xiaomi_cloud.py", line 60, in login
    return await self._get_notification_url(notification_url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_gateway3/core/xiaomi_cloud.py", line 185, in _get_notification_url
    return await self._send_ticket(flag, r.cookies["identity_session"])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_gateway3/core/xiaomi_cloud.py", line 221, in _send_ticket
    assert res2["code"] == 0, res2
           ^^^^^^^^^^^^^^^^^
AssertionError: {'code': 70022, 'desc': '发送验证码失败', 'tips': 'Запрошено слишком много кодов. Повторите попытку завтра.', 'title': '', 'action': ''}
